name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Check out code
        uses: actions/checkout@v3

      # Instalar Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      # Subir os serviços definidos no docker-compose.yml
      - name: Run Docker Compose
        run: docker-compose up -d

      # Esperar Postgres estar disponível
      - name: Wait for Postgres
        run: until nc -z localhost 5432; do sleep 1; done

      # Configuração da versão do Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache para dependências do Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build da aplicação
      - name: Build with Maven
        run: mvn clean install

      # Executar testes
      - name: Run tests
        run: mvn test

      # Derrubar os containers no final
      - name: Tear down Docker Compose
        run: docker-compose down
