name: CI Pipeline

# Quando rodar a pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Definição dos jobs que serão executados
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do código-fonte
      - name: Check out code
        uses: actions/checkout@v3

      # Configuração da versão do Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache para dependências do Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build e teste da aplicação
      - name: Build with Maven
        run: mvn clean install

      # Executar testes
      - name: Run tests
        run: mvn test
